# Generated by Django 5.2.3 on 2025-08-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
