# Generated by Django 5.2.3 on 2025-08-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_owner_pet_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner_id',
            new_name='ownerID',
        ),
    ]
