# Generated by Django 5.2.3 on 2025-08-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_rename_owner_id_pet_ownerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='ownerID',
            new_name='ownerId',
        ),
    ]
