# Generated by Django 5.2.3 on 2025-08-18 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_ownerid_pet_ownerid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_log',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='vet_details',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='food_log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_log',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vet_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet_details',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
