# Generated by Django 5.2.3 on 2025-08-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_food_log_options_alter_vet_details_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_log',
            options={'ordering': ['logged_time']},
        ),
    ]
