# Generated by Django 5.2.3 on 2025-08-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_food_log_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_log',
            options={'ordering': ['-logged_time']},
        ),
    ]
