# Generated by Django 5.2.3 on 2025-09-07 21:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_appointment_vetvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('vaccinations', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='pets.pet')),
            ],
        ),
    ]
