# Generated by Django 5.2.3 on 2025-09-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_pethealth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='vetvisit',
            options={'ordering': ['created_at']},
        ),
    ]
