# Generated by Django 5.2.3 on 2025-09-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_appointment_options_alter_vetvisit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pethealth',
            options={'ordering': ['created_at']},
        ),
    ]
