# Generated by Django 5.2.3 on 2025-09-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_pethealth_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date']},
        ),
        migrations.AlterModelOptions(
            name='pethealth',
            options={'ordering': ['-record_date']},
        ),
        migrations.AlterModelOptions(
            name='vetvisit',
            options={'ordering': ['-visit_date']},
        ),
    ]
