# Generated by Django 5.2.3 on 2025-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_vet_details_pet_vets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
