# Generated by Django 5.2.3 on 2025-06-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
    ]
