# Generated by Django 5.2.3 on 2025-07-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_options_pet_created_at_pet_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
