# Generated by Django 5.2.3 on 2025-07-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_pet_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('fish', 'Fish'), ('bird', 'Bird')], max_length=255),
        ),
    ]
