# Generated by Django 5.2.3 on 2025-07-13 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_breed_alter_pet_name_alter_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet_details',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
